import type {
  User,
  School,
  Student,
  Teacher,
  ClassGroup,
  Subject,
  Payment,
  FeeStructure,
  Grade,
  Message,
  Notification,
} from "@/types";

// ---- USERS ----
export const currentUser: User = {
  id: "usr_01",
  firstName: "Fatou",
  lastName: "Ndiaye",
  email: "fatou.ndiaye@edusaas.sn",
  role: "SCHOOL_ADMIN",
  schoolId: "sch_01",
  schoolName: "College Sainte-Marie",
  country: "SN",
  avatar: null,
};

export const mockUsers: User[] = [
  currentUser,
  {
    id: "usr_02",
    firstName: "Amadou",
    lastName: "Diallo",
    email: "amadou.diallo@edusaas.sn",
    role: "ACCOUNTANT",
    schoolId: "sch_01",
    schoolName: "College Sainte-Marie",
    country: "SN",
    avatar: null,
  },
  {
    id: "usr_03",
    firstName: "Marie",
    lastName: "Faye",
    email: "marie.faye@edusaas.sn",
    role: "TEACHER",
    schoolId: "sch_01",
    schoolName: "College Sainte-Marie",
    country: "SN",
    avatar: null,
  },
  {
    id: "usr_04",
    firstName: "Ousmane",
    lastName: "Camara",
    email: "ousmane.camara@edusaas.sn",
    role: "PARENT",
    schoolId: "sch_01",
    schoolName: "College Sainte-Marie",
    country: "SN",
    avatar: null,
  },
  {
    id: "usr_05",
    firstName: "Ibrahima",
    lastName: "Sow",
    email: "ibrahima.sow@edusaas.sn",
    role: "SUPER_ADMIN",
    schoolId: null,
    schoolName: null,
    country: "SN",
    avatar: null,
  },
];

// ---- SCHOOLS ----
export const mockSchools: School[] = [
  {
    id: "sch_01",
    name: "College Sainte-Marie",
    country: "SN",
    city: "Dakar",
    address: "Rue 12, Medina",
    phone: "+221 77 123 45 67",
    email: "contact@sainte-marie.sn",
    subscriptionStatus: "ACTIVE",
    studentsCount: 342,
    teachersCount: 24,
    createdAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "sch_02",
    name: "Ecole Les Colombes",
    country: "CI",
    city: "Abidjan",
    address: "Cocody, Riviera 2",
    phone: "+225 07 89 12 34 56",
    email: "contact@colombes.ci",
    subscriptionStatus: "ACTIVE",
    studentsCount: 215,
    teachersCount: 16,
    createdAt: "2024-10-15T00:00:00Z",
  },
  {
    id: "sch_03",
    name: "Institut Al-Azhar",
    country: "SN",
    city: "Thies",
    address: "Avenue Leopold Sedar Senghor",
    phone: "+221 76 456 78 90",
    email: "info@al-azhar.sn",
    subscriptionStatus: "TRIAL",
    studentsCount: 128,
    teachersCount: 10,
    createdAt: "2025-01-05T00:00:00Z",
  },
  {
    id: "sch_04",
    name: "Complexe Scolaire La Reussite",
    country: "CM",
    city: "Douala",
    address: "Akwa, Rue du Commerce",
    phone: "+237 6 99 88 77 66",
    email: "contact@lareussite.cm",
    subscriptionStatus: "EXPIRED",
    studentsCount: 89,
    teachersCount: 8,
    createdAt: "2024-06-20T00:00:00Z",
  },
];

// ---- STUDENTS ----
export const mockStudents: Student[] = [
  {
    id: "std_01",
    registrationNo: "0241",
    firstName: "Fatou",
    lastName: "Camara",
    gender: "FEMALE",
    dateOfBirth: "2012-03-15",
    className: "6eme A",
    classId: "cls_01",
    photo: null,
    isActive: true,
    parentName: "Ousmane Camara",
    parentPhone: "+221 77 234 56 78",
  },
  {
    id: "std_02",
    registrationNo: "0242",
    firstName: "Moussa",
    lastName: "Diop",
    gender: "MALE",
    dateOfBirth: "2011-07-22",
    className: "6eme A",
    classId: "cls_01",
    photo: null,
    isActive: true,
    parentName: "Awa Diop",
    parentPhone: "+221 78 345 67 89",
  },
  {
    id: "std_03",
    registrationNo: "0243",
    firstName: "Aminata",
    lastName: "Ba",
    gender: "FEMALE",
    dateOfBirth: "2012-11-05",
    className: "6eme B",
    classId: "cls_02",
    photo: null,
    isActive: true,
    parentName: "Mamadou Ba",
    parentPhone: "+221 76 456 78 90",
  },
  {
    id: "std_04",
    registrationNo: "0244",
    firstName: "Ibrahima",
    lastName: "Ndiaye",
    gender: "MALE",
    dateOfBirth: "2011-01-30",
    className: "5eme A",
    classId: "cls_03",
    photo: null,
    isActive: true,
    parentName: "Mariama Ndiaye",
    parentPhone: "+221 77 567 89 01",
  },
  {
    id: "std_05",
    registrationNo: "0245",
    firstName: "Aissatou",
    lastName: "Sow",
    gender: "FEMALE",
    dateOfBirth: "2012-06-18",
    className: "5eme A",
    classId: "cls_03",
    photo: null,
    isActive: false,
    parentName: "Abdoulaye Sow",
    parentPhone: "+221 78 678 90 12",
  },
  {
    id: "std_06",
    registrationNo: "0246",
    firstName: "Cheikh",
    lastName: "Fall",
    gender: "MALE",
    dateOfBirth: "2011-09-12",
    className: "4eme A",
    classId: "cls_04",
    photo: null,
    isActive: true,
    parentName: "Ndene Fall",
    parentPhone: "+221 76 789 01 23",
  },
  {
    id: "std_07",
    registrationNo: "0247",
    firstName: "Mariama",
    lastName: "Toure",
    gender: "FEMALE",
    dateOfBirth: "2012-12-01",
    className: "6eme A",
    classId: "cls_01",
    photo: null,
    isActive: true,
    parentName: "Sekou Toure",
    parentPhone: "+221 77 890 12 34",
  },
  {
    id: "std_08",
    registrationNo: "0248",
    firstName: "Oumar",
    lastName: "Sy",
    gender: "MALE",
    dateOfBirth: "2011-04-25",
    className: "6eme B",
    classId: "cls_02",
    photo: null,
    isActive: true,
    parentName: "Fatima Sy",
    parentPhone: "+221 78 901 23 45",
  },
];

// ---- CLASSES ----
export const mockClasses: ClassGroup[] = [
  { id: "cls_01", name: "6eme A", level: "6eme", studentsCount: 35, teacherName: "Marie Faye" },
  { id: "cls_02", name: "6eme B", level: "6eme", studentsCount: 33, teacherName: "Jean Mendy" },
  { id: "cls_03", name: "5eme A", level: "5eme", studentsCount: 30, teacherName: "Pierre Diatta" },
  { id: "cls_04", name: "4eme A", level: "4eme", studentsCount: 28, teacherName: "Aida Gueye" },
  { id: "cls_05", name: "3eme A", level: "3eme", studentsCount: 32, teacherName: "Lamine Diouf" },
];

// ---- SUBJECTS ----
export const mockSubjects: Subject[] = [
  { id: "sub_01", name: "Mathematiques", coefficient: 4, classId: "cls_01", className: "6eme A", teacherName: "Marie Faye" },
  { id: "sub_02", name: "Francais", coefficient: 4, classId: "cls_01", className: "6eme A", teacherName: "Jean Mendy" },
  { id: "sub_03", name: "Sciences de la Vie et de la Terre", coefficient: 2, classId: "cls_01", className: "6eme A", teacherName: "Pierre Diatta" },
  { id: "sub_04", name: "Histoire-Geographie", coefficient: 2, classId: "cls_01", className: "6eme A", teacherName: "Aida Gueye" },
  { id: "sub_05", name: "Anglais", coefficient: 2, classId: "cls_01", className: "6eme A", teacherName: "Lamine Diouf" },
  { id: "sub_06", name: "Education Physique", coefficient: 1, classId: "cls_01", className: "6eme A", teacherName: "Ibrahima Kane" },
];

// ---- TEACHERS ----
export const mockTeachers: Teacher[] = [
  { id: "tch_01", firstName: "Marie", lastName: "Faye", email: "marie.faye@sainte-marie.sn", phone: "+221 77 111 22 33", subjects: ["Mathematiques"], classes: ["6eme A", "6eme B"], isActive: true },
  { id: "tch_02", firstName: "Jean", lastName: "Mendy", email: "jean.mendy@sainte-marie.sn", phone: "+221 78 222 33 44", subjects: ["Francais"], classes: ["6eme A", "5eme A"], isActive: true },
  { id: "tch_03", firstName: "Pierre", lastName: "Diatta", email: "pierre.diatta@sainte-marie.sn", phone: "+221 76 333 44 55", subjects: ["SVT"], classes: ["6eme A", "4eme A"], isActive: true },
  { id: "tch_04", firstName: "Aida", lastName: "Gueye", email: "aida.gueye@sainte-marie.sn", phone: "+221 77 444 55 66", subjects: ["Histoire-Geographie"], classes: ["5eme A", "3eme A"], isActive: true },
  { id: "tch_05", firstName: "Lamine", lastName: "Diouf", email: "lamine.diouf@sainte-marie.sn", phone: "+221 78 555 66 77", subjects: ["Anglais"], classes: ["6eme A", "6eme B", "5eme A"], isActive: false },
];

// ---- PAYMENTS ----
export const mockPayments: Payment[] = [
  {
    id: "pay_01",
    studentId: "std_01",
    studentName: "Fatou Camara",
    className: "6eme A",
    installmentName: "1ere tranche",
    amount: 85000,
    currency: "XOF",
    method: "MOBILE_MONEY",
    operator: "WAVE",
    status: "COMPLETED",
    paidAt: "2025-02-10T10:23:00Z",
    invoiceNumber: "REC-2025-00142",
  },
  {
    id: "pay_02",
    studentId: "std_02",
    studentName: "Moussa Diop",
    className: "6eme A",
    installmentName: "1ere tranche",
    amount: 85000,
    currency: "XOF",
    method: "CASH",
    operator: null,
    status: "COMPLETED",
    paidAt: "2025-02-08T14:10:00Z",
    invoiceNumber: "REC-2025-00140",
  },
  {
    id: "pay_03",
    studentId: "std_03",
    studentName: "Aminata Ba",
    className: "6eme B",
    installmentName: "1ere tranche",
    amount: 85000,
    currency: "XOF",
    method: "MOBILE_MONEY",
    operator: "ORANGE_MONEY",
    status: "PENDING",
    paidAt: "2025-02-12T09:45:00Z",
    invoiceNumber: "REC-2025-00145",
  },
  {
    id: "pay_04",
    studentId: "std_04",
    studentName: "Ibrahima Ndiaye",
    className: "5eme A",
    installmentName: "2eme tranche",
    amount: 75000,
    currency: "XOF",
    method: "BANK_TRANSFER",
    operator: null,
    status: "COMPLETED",
    paidAt: "2025-01-20T11:00:00Z",
    invoiceNumber: "REC-2025-00120",
  },
  {
    id: "pay_05",
    studentId: "std_05",
    studentName: "Aissatou Sow",
    className: "5eme A",
    installmentName: "1ere tranche",
    amount: 75000,
    currency: "XOF",
    method: "MOBILE_MONEY",
    operator: "MTN_MOMO",
    status: "FAILED",
    paidAt: "2025-02-14T16:30:00Z",
    invoiceNumber: "REC-2025-00148",
  },
  {
    id: "pay_06",
    studentId: "std_06",
    studentName: "Cheikh Fall",
    className: "4eme A",
    installmentName: "1ere tranche",
    amount: 95000,
    currency: "XOF",
    method: "MOBILE_MONEY",
    operator: "WAVE",
    status: "COMPLETED",
    paidAt: "2025-02-05T08:15:00Z",
    invoiceNumber: "REC-2025-00135",
  },
  {
    id: "pay_07",
    studentId: "std_07",
    studentName: "Mariama Toure",
    className: "6eme A",
    installmentName: "1ere tranche",
    amount: 85000,
    currency: "XOF",
    method: "CHECK",
    operator: null,
    status: "COMPLETED",
    paidAt: "2025-02-01T10:00:00Z",
    invoiceNumber: "REC-2025-00130",
  },
  {
    id: "pay_08",
    studentId: "std_08",
    studentName: "Oumar Sy",
    className: "6eme B",
    installmentName: "2eme tranche",
    amount: 85000,
    currency: "XOF",
    method: "MOBILE_MONEY",
    operator: "WAVE",
    status: "PENDING",
    paidAt: "2025-02-15T13:20:00Z",
    invoiceNumber: "REC-2025-00150",
  },
];

// ---- FEE STRUCTURES ----
export const mockFeeStructures: FeeStructure[] = [
  {
    id: "fee_01",
    className: "6eme A",
    totalAmount: 255000,
    installments: [
      { id: "inst_01", name: "1ere tranche", amount: 85000, dueDate: "2024-10-15" },
      { id: "inst_02", name: "2eme tranche", amount: 85000, dueDate: "2025-01-15" },
      { id: "inst_03", name: "3eme tranche", amount: 85000, dueDate: "2025-04-15" },
    ],
  },
  {
    id: "fee_02",
    className: "5eme A",
    totalAmount: 225000,
    installments: [
      { id: "inst_04", name: "1ere tranche", amount: 75000, dueDate: "2024-10-15" },
      { id: "inst_05", name: "2eme tranche", amount: 75000, dueDate: "2025-01-15" },
      { id: "inst_06", name: "3eme tranche", amount: 75000, dueDate: "2025-04-15" },
    ],
  },
];

// ---- GRADES ----
export const mockGrades: Grade[] = [
  { id: "grd_01", studentId: "std_01", studentName: "Fatou Camara", evaluationTitle: "Devoir n2", evaluationType: "CLASS_TEST", subjectName: "Mathematiques", score: 16, maxScore: 20, coefficient: 1, isAbsent: false, comment: "Excellent travail", createdAt: "2025-02-10T00:00:00Z" },
  { id: "grd_02", studentId: "std_01", studentName: "Fatou Camara", evaluationTitle: "Examen semestriel", evaluationType: "EXAM", subjectName: "Francais", score: 14, maxScore: 20, coefficient: 2, isAbsent: false, comment: "Bonne copie", createdAt: "2025-02-05T00:00:00Z" },
  { id: "grd_03", studentId: "std_02", studentName: "Moussa Diop", evaluationTitle: "Devoir n2", evaluationType: "CLASS_TEST", subjectName: "Mathematiques", score: 12, maxScore: 20, coefficient: 1, isAbsent: false, comment: "Peut mieux faire", createdAt: "2025-02-10T00:00:00Z" },
  { id: "grd_04", studentId: "std_03", studentName: "Aminata Ba", evaluationTitle: "Devoir n2", evaluationType: "CLASS_TEST", subjectName: "Mathematiques", score: 18, maxScore: 20, coefficient: 1, isAbsent: false, comment: "Tres bien", createdAt: "2025-02-10T00:00:00Z" },
  { id: "grd_05", studentId: "std_04", studentName: "Ibrahima Ndiaye", evaluationTitle: "Devoir n1", evaluationType: "CLASS_TEST", subjectName: "SVT", score: 8, maxScore: 20, coefficient: 1, isAbsent: false, comment: "Insuffisant", createdAt: "2025-01-20T00:00:00Z" },
  { id: "grd_06", studentId: "std_05", studentName: "Aissatou Sow", evaluationTitle: "Devoir n2", evaluationType: "CLASS_TEST", subjectName: "Mathematiques", score: 15, maxScore: 20, coefficient: 1, isAbsent: false, comment: "Bon travail", createdAt: "2025-02-10T00:00:00Z" },
  { id: "grd_07", studentId: "std_01", studentName: "Fatou Camara", evaluationTitle: "Devoir n1", evaluationType: "CLASS_TEST", subjectName: "SVT", score: 13, maxScore: 20, coefficient: 1, isAbsent: false, comment: "Assez bien", createdAt: "2025-01-18T00:00:00Z" },
  { id: "grd_08", studentId: "std_02", studentName: "Moussa Diop", evaluationTitle: "Examen semestriel", evaluationType: "EXAM", subjectName: "Francais", score: 9, maxScore: 20, coefficient: 2, isAbsent: false, comment: "A revoir", createdAt: "2025-02-05T00:00:00Z" },
];

// ---- MESSAGES ----
export const mockMessages: Message[] = [
  {
    id: "msg_01",
    senderId: "usr_03",
    senderName: "Marie Faye",
    senderRole: "TEACHER",
    receiverId: "usr_04",
    receiverName: "Ousmane Camara",
    content: "Bonjour M. Camara. Fatou a obtenu 16/20 au dernier devoir de maths. Felicitations !",
    isRead: true,
    createdAt: "2025-02-10T14:30:00Z",
  },
  {
    id: "msg_02",
    senderId: "usr_04",
    senderName: "Ousmane Camara",
    senderRole: "PARENT",
    receiverId: "usr_03",
    receiverName: "Marie Faye",
    content: "Merci beaucoup Mme Faye. Nous sommes tres fiers d'elle. Comment se comporte-t-elle en classe ?",
    isRead: true,
    createdAt: "2025-02-10T15:00:00Z",
  },
  {
    id: "msg_03",
    senderId: "usr_03",
    senderName: "Marie Faye",
    senderRole: "TEACHER",
    receiverId: "usr_04",
    receiverName: "Ousmane Camara",
    content: "Elle est tres attentive et participe regulierement. Continuez a l'encourager.",
    isRead: false,
    createdAt: "2025-02-10T15:15:00Z",
  },
  {
    id: "msg_04",
    senderId: "usr_01",
    senderName: "Fatou Ndiaye",
    senderRole: "SCHOOL_ADMIN",
    receiverId: "usr_04",
    receiverName: "Ousmane Camara",
    content: "Rappel : la reunion des parents d'eleves aura lieu le samedi 22 fevrier a 10h.",
    isRead: false,
    createdAt: "2025-02-12T09:00:00Z",
  },
];

// ---- NOTIFICATIONS ----
export const mockNotifications: Notification[] = [
  {
    id: "notif_01",
    title: "Paiement recu",
    message: "Le paiement de 85 000 F CFA de Fatou Camara a ete confirme.",
    type: "SUCCESS",
    isRead: false,
    createdAt: "2025-02-10T10:25:00Z",
  },
  {
    id: "notif_02",
    title: "Echeance proche",
    message: "La 2eme tranche de 15 eleves arrive a echeance dans 7 jours.",
    type: "WARNING",
    isRead: false,
    createdAt: "2025-02-08T08:00:00Z",
  },
  {
    id: "notif_03",
    title: "Notes saisies",
    message: "Mme Faye a saisi les notes du devoir n2 de Mathematiques pour la 6eme A.",
    type: "INFO",
    isRead: true,
    createdAt: "2025-02-10T16:00:00Z",
  },
  {
    id: "notif_04",
    title: "Paiement echoue",
    message: "Le paiement MTN MoMo de Aissatou Sow a echoue. Veuillez reessayer.",
    type: "ERROR",
    isRead: false,
    createdAt: "2025-02-14T16:35:00Z",
  },
];

// ---- REVENUE DATA (for charts) ----
export const monthlyRevenueData = [
  { month: "Sept", montant: 4200000 },
  { month: "Oct", montant: 6800000 },
  { month: "Nov", montant: 3500000 },
  { month: "Dec", montant: 2100000 },
  { month: "Jan", montant: 5400000 },
  { month: "Fev", montant: 4800000 },
];

export const recoveryData = [
  { name: "Recouvre", value: 68, fill: "#15803D" },
  { name: "En attente", value: 22, fill: "#22C55E" },
  { name: "Impaye", value: 10, fill: "#BBF7D0" },
];

export const gradeDistributionData = [
  { range: "0-5", count: 2 },
  { range: "5-10", count: 5 },
  { range: "10-12", count: 8 },
  { range: "12-14", count: 12 },
  { range: "14-16", count: 15 },
  { range: "16-18", count: 10 },
  { range: "18-20", count: 4 },
];
